version: '3.8'

services:
  nestjs-mongodb:
    container_name: nestjs-mongodb
    build:
      context: .
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped